export const companyPolicy = `By clicking ‘Continue’ you consent to our collection, use and handling of your personal information in accordance with the Privacy Statement and Privacy Policy]`;
export const headerTitle = "Covid-19 Vaccine Tracker";
export const privacyHeader = `Downer is required to comply with its obligations under public health orders and directions of each State and Territory, work health and safety laws, and its agreements and contracts with customers. To facilitate these purposes, we are collecting your personal information.`;

export const privacyStatementHtml = `<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">Privacy Statement</span></span></strong></p>
<p style="text-align: left;"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">This Privacy Statement explains how Downer&nbsp;</span><span data-ccp-parastyle="Body Text">and its related bodies corporate (</span></span><strong><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Downer</span><span data-ccp-parastyle="Body Text">, we</span></span></strong><span data-contrast="auto"><span data-ccp-parastyle="Body Text">)</span><span data-ccp-parastyle="Body Text">&nbsp;will manage the personal information of its&nbsp;</span><span data-ccp-parastyle="Body Text">employees, contractors and subcontractors&nbsp;</span><span data-ccp-parastyle="Body Text">and&nbsp;</span><span data-ccp-parastyle="Body Text">persons wishing to access or enter</span><span data-ccp-parastyle="Body Text">&nbsp;Downer work locations&nbsp;</span><span data-ccp-parastyle="Body Text">in relation to their</span><span data-ccp-parastyle="Body Text">&nbsp;COVID-19 status, including</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;&nbsp;&nbsp;</span><span data-ccp-parastyle="Body Text">COVID-19</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">vaccination</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">status and testing details,</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">consistent</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">with</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">its</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">obligations under</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">the</span><span data-ccp-parastyle="Body Text">&nbsp;</span></span><em><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Privacy</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">Act</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">1988</span><span data-ccp-parastyle="Body Text">&nbsp;</span></span></em><span data-contrast="auto"><span data-ccp-parastyle="Body Text">(</span><span data-ccp-parastyle="Body Text">Cth</span><span data-ccp-parastyle="Body Text">).</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:808}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:347}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">The</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">purpose</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">of collecting</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">this</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We are</span><span data-ccp-parastyle="Body Text">&nbsp;required to comply with&nbsp;</span><span data-ccp-parastyle="Body Text">our&nbsp;</span><span data-ccp-parastyle="Body Text">obligations under:</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:132}">&nbsp;</span></p>
<ul>
<li data-leveltext="" data-font="Symbol" data-listid="2" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Public health orders and directions of each State and Territory</span></span><span data-ccp-props="{&quot;335559737&quot;:164}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="2" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Work health and safety laws</span></span><span data-ccp-props="{&quot;335559737&quot;:164}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="2" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Our&nbsp;</span><span data-ccp-parastyle="Body Text">agreements and contracts with customers.</span></span><span data-ccp-props="{&quot;335559737&quot;:164}">&nbsp;</span></li>
</ul>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Examples include:</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:347}">&nbsp;</span></p>
<ul>
<li data-leveltext="" data-font="Symbol" data-listid="3" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Complying with public health orders and directions relating to &lsquo;local government areas of concern&rsquo;, health and hospital services, and aged care</span></span><span data-ccp-props="{&quot;335559737&quot;:347}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="3" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Complying with&nbsp;</span><span data-ccp-parastyle="Body Text">our</span><span data-ccp-parastyle="Body Text">&nbsp;obligations under agreements and contracts with customers that require&nbsp;</span><span data-ccp-parastyle="Body Text">w</span><span data-ccp-parastyle="Body Text">orkers</span><span data-ccp-parastyle="Body Text">&nbsp;to provide status of COVID-19 vaccination status or COVID-19</span><span data-ccp-parastyle="Body Text">&nbsp;tests</span></span><span data-ccp-props="{&quot;335559737&quot;:347}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="3" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">T</span><span data-ccp-parastyle="Body Text">o&nbsp;</span><span data-ccp-parastyle="Body Text">facilitate the carrying out of risk assessments associated&nbsp;</span><span data-ccp-parastyle="Body Text">with&nbsp;</span><span data-ccp-parastyle="Body Text">COVID-19 in the workplace, in compliance with work, health and safety laws</span></span><span data-ccp-props="{&quot;335559737&quot;:347}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="3" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">To&nbsp;</span><span data-ccp-parastyle="Body Text">maintain a safe workplace for our&nbsp;</span><span data-ccp-parastyle="Body Text">w</span><span data-ccp-parastyle="Body Text">orkers and visitors</span><span data-ccp-parastyle="Body Text">, in compliance with work, health and safety laws.</span></span><span data-ccp-props="{&quot;335559737&quot;:347}">&nbsp;</span></li>
</ul>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">To facilitate these purposes, we are collecting your personal information&nbsp;</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:132}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:11}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">Personal</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">collected</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">about your</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">COVID-19</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">status</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We will collect some or&nbsp;</span><span data-ccp-parastyle="Body Text">all of</span><span data-ccp-parastyle="Body Text">&nbsp;the following personal information:</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:132}">&nbsp;</span></p>
<ul>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Employee number (if you have&nbsp;a&nbsp;Downer employee number)</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559738&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">full&nbsp;name&nbsp;and position</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">date of birth</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559738&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">email address</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559738&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">contact number</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">your employer (if you do not have an employee number)</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559738&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">your COVID-19 Vaccination Certificate(s) and history</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559738&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">details of your COVID-19 testing, including date/time of testing, and test results</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">information relating to your compliance with the public health orders and directions, and the requirements of Downer&rsquo;s&nbsp;agreements and&nbsp;contracts&nbsp;with its customers</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">information required for Downer to meet its work health and safety obligations&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
</ul>
<p><span data-ccp-props="{&quot;335559737&quot;:132}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">What happens</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">if</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">this</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">is</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">not</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">provided?</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">If</span><span data-ccp-parastyle="Body Text">&nbsp;you choose not to provide&nbsp;</span><span data-ccp-parastyle="Body Text">us</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">with this information</span><span data-ccp-parastyle="Body Text">&nbsp;and it is a requirement of your role that you are vaccinated for COVID-19</span><span data-ccp-parastyle="Body Text">,</span><span data-ccp-parastyle="Body Text">&nbsp;we</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">may&nbsp;</span><span data-ccp-parastyle="Body Text">need to&nbsp;</span><span data-ccp-parastyle="Body Text">prohibit you from&nbsp;</span><span data-ccp-parastyle="Body Text">accessing&nbsp;</span><span data-ccp-parastyle="Body Text">your</span><span data-ccp-parastyle="Body Text">&nbsp;work&nbsp;</span><span data-ccp-parastyle="Body Text">location</span><span data-ccp-parastyle="Body Text">&nbsp;or performing your usual duties</span><span data-ccp-parastyle="Body Text">.</span><span data-ccp-parastyle="Body Text">&nbsp;</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:164}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">If public health orders or directions are not complied with, it may place you and or Downer at risk of non-compliance with that legal requirement.&nbsp;</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:164}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:1}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">Use</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">and disclosure</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">of</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">personal</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We will use and disclose the information collected to the extent required to</span><span data-ccp-parastyle="Body Text">:</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:596,&quot;335559738&quot;:1}">&nbsp;</span></p>
<ul>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">further the purposes above</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
<li data-leveltext="" data-font="Symbol" data-listid="1" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">comply&nbsp;(and evidence compliance with)&nbsp;with the&nbsp;relevant&nbsp;public health orders and directions, requirements of customer contracts, and&nbsp;work,&nbsp;health&nbsp;and safety laws</span><span data-ccp-props="{&quot;201341983&quot;:1,&quot;335559740&quot;:268,&quot;335559991&quot;:361,&quot;469777462&quot;:[821,822],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[1,1]}">&nbsp;</span></li>
</ul>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We&nbsp;</span><span data-ccp-parastyle="Body Text">may also</span><span data-ccp-parastyle="Body Text">&nbsp;use and disclose information about your&nbsp;</span><span data-ccp-parastyle="Body Text">v</span><span data-ccp-parastyle="Body Text">accination&nbsp;</span><span data-ccp-parastyle="Body Text">s</span><span data-ccp-parastyle="Body Text">tatus internally to evaluate&nbsp;</span><span data-ccp-parastyle="Body Text">the</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">coverage</span><span data-ccp-parastyle="Body Text">&nbsp;of vaccinations at&nbsp;</span><span data-ccp-parastyle="Body Text">Downer</span><span data-ccp-parastyle="Body Text">, enabling us to better undertake risk assessments to</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">determine and implement appropriate control measures and protocols to minimise the risk to our</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">w</span><span data-ccp-parastyle="Body Text">orkers</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">and visitors.</span><span data-ccp-parastyle="Body Text">&nbsp;</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:596,&quot;335559738&quot;:1}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We may use or provide de-identified data&nbsp;</span><span data-ccp-parastyle="Body Text">for</span><span data-ccp-parastyle="Body Text">&nbsp;other purposes, including to government departments or representatives&nbsp;</span><span data-ccp-parastyle="Body Text">where</span><span data-ccp-parastyle="Body Text">&nbsp;requested&nbsp;</span><span data-ccp-parastyle="Body Text">to&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">do</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">so and/or</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">to</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">incorporate into</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">internal</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">board</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">or</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">committees</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">for</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">reporting</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">purposes, or to facilitate the roll-out of the COVID-19 vaccine to&nbsp;</span><span data-ccp-parastyle="Body Text">our</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">w</span><span data-ccp-parastyle="Body Text">orkers.</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:400}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">We will not use information about your&nbsp;</span><span data-ccp-parastyle="Body Text">COVID-19 status</span><span data-ccp-parastyle="Body Text">, or disclose it to any third parties, for&nbsp;</span><span data-ccp-parastyle="Body Text">any</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">o</span><span data-ccp-parastyle="Body Text">the</span><span data-ccp-parastyle="Body Text">r</span><span data-ccp-parastyle="Body Text">&nbsp;purpose without your consent, unless we are legally required or authorised by law</span><span data-ccp-parastyle="Body Text">,</span><span data-ccp-parastyle="Body Text">&nbsp;or&nbsp;</span><span data-ccp-parastyle="Body Text">another</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">exception</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">applies under</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">the Privacy</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">Act.</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:400}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:2}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">How your</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">is stored</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">Downer will store information&nbsp;</span><span data-ccp-parastyle="Body Text">about your&nbsp;</span><span data-ccp-parastyle="Body Text">COVID-19 s</span><span data-ccp-parastyle="Body Text">tatus in a secure environment within Australia</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">which is protected by strict access control mechanisms.&nbsp;</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:554}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:1}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">You</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">can</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">access</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">or correct</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">your</span><span data-ccp-parastyle="heading 1">&nbsp;</span><span data-ccp-parastyle="heading 1">information</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p style="text-align: left;"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">You can access or correct the information about your&nbsp;</span><span data-ccp-parastyle="Body Text">COVID-19 status</span><span data-ccp-parastyle="Body Text">&nbsp;by contacting your HR</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;b</span><span data-ccp-parastyle="Body Text">usiness partner.</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:763,&quot;335559738&quot;:1}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:10}">&nbsp;</span></p>
<p style="text-align: center;"><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 1">Complaints</span></span></strong><span data-ccp-props="{&quot;335559685&quot;:101}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">If you wish to make a complaint about the way your personal information has been managed, you</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">can contact your HR business partner</span><span data-ccp-parastyle="Body Text">&nbsp;in the first instance</span><span data-ccp-parastyle="Body Text">. Please provide as much information as possible so we&nbsp;</span><span data-ccp-parastyle="Body Text">can</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">investigate</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">and</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">respond.</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:449,&quot;335559738&quot;:1}">&nbsp;</span></p>
<p><span data-contrast="auto"><span data-ccp-parastyle="Body Text">A complaint can also be made to Downer&rsquo;s Privacy Officer.</span></span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:449,&quot;335559738&quot;:1}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335559738&quot;:10}">&nbsp;</span></p>
<p style="text-align: center;"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">If you are not satisfied with our response, you can contact the&nbsp;</span></span><a href="https://www.oaic.gov.au/privacy/privacy-complaints/"><span data-contrast="none"><span data-ccp-parastyle="Body Text">Office of the Australian Information</span></span></a><span data-contrast="none"><span data-ccp-parastyle="Body Text">&nbsp;</span></span><a href="https://www.oaic.gov.au/privacy/privacy-complaints/"><span data-contrast="none"><span data-ccp-parastyle="Body Text">Commissioner.</span></span></a><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:101,&quot;335559737&quot;:478}">&nbsp;</span></p>
<p style="text-align: center;"><span data-contrast="auto"><span data-ccp-parastyle="Body Text">This Privacy&nbsp;</span><span data-ccp-parastyle="Body Text">Statement&nbsp;</span><span data-ccp-parastyle="Body Text">provides specific information about the handling of personal information in</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">relation to an individual&rsquo;s COVID-19&nbsp;</span><span data-ccp-parastyle="Body Text">s</span><span data-ccp-parastyle="Body Text">tatus only. For more information about the way</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">Downer&nbsp;</span><span data-ccp-parastyle="Body Text">generally</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">handles personal</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">information,</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">see</span><span data-ccp-parastyle="Body Text">&nbsp;</span><span data-ccp-parastyle="Body Text">our&nbsp;</span><span data-ccp-parastyle="Body Text">Privacy Policy</span></span><span data-ccp-props="{&quot;335559685&quot;:101,&quot;335559737&quot;:604,&quot;335559738&quot;:93}">&nbsp;</span></p>`;
