export enum ErrorKeyEnum {
  INPUT_CODE = "INPUT_CODE",
  GET_EMPLOYEE = " GET_EMPLOYEE",
  EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND",
  CREATE_VACCINATION = "CREATE_VACCINATION",
  UPDATE_VACCINATION = "CREATE_VACCINATION",
  GET_VACCINATION = "GET_VACCINATION",
}

export interface IError {
  [key: string]: string;
}
